[package]
name = "Ultimate Neko"
version = "2.0.0"
author = "CV Master"

[sprite]
width = 256
height = 256
fps = 8

[[animations]]
name = "alert"
sheet = "sprites/pet.png"
frames = 40

[[animations]]
name = "happy"
sheet = "sprites/happy.png"
frames = 40

[[animations]]
name = "idle"
sheet = "sprites/idle.png"
frames = 40

[[animations]]
name = "sleep"
sheet = "sprites/sleep.png"
frames = 40

[[animations]]
name = "walk_left"
sheet = "sprites/walk_left.png"
frames = 40

[[animations]]
name = "walk_right"
sheet = "sprites/walk_right.png"
frames = 40

[[animations]]
name = "trans1"
sheet = "sprites/trans1.png"
frames = 40

[[animations]]
name = "trans_to_sleep"
sheet = "sprites/trans_to_sleep.png"
frames = 39